# Dependencies
markdown:	kramdown
highlighter:	pygments

# Permalinks
permalink:	/blog/:title

# Setup
title:		big balls of mud killer
tagline:	'blog'
description:	'My personal blog.'
url:		http://freedrool.us/
commentsystem:	google
disqus:		example

author :
  name : Tony Miller
  email : mcfiredrill@gmail.com
  github : mcfiredrill
  twitter : freedrull

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.png

social:
  - icon:	twitter
    url:	https://twitter.com/freedrull
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/mcfiredrill
    desc:	Fork me on github

  - icon:	feed
    url:	http://freedrool.us/atom.xml
    desc:	Subscribe to my feed

menu:
  - title:	Home
    url:	/

  - title:	About
    url:	/about.html

copyright:
  author:	freedrool
  url:		http://freedrool.us

# Google Analytics
google_analytics: 'UA-40007409-1'
